1.0
vertex_source_file sway.vert
fragment_source_file sway.frag

uniform u_t_modelViewProjection T_MODEL_VIEW_PROJECTION

uniform u_m_diffuseTexture M_DIFFUSE_TEXTURE
uniform u_m_diffuseColour M_DIFFUSE_COLOUR
uniform u_m_opacity M_OPACITY
uniform u_swaySpeed SWAYING_SPEED
uniform u_swayDepth SWAYING_DEPTH
uniform u_swayPhase SWAYING_PHASE
uniform u_time TIME
uniform u_uvCoordOffsetScale M_UV_OFFSET_SCALE
